set nocompatible
execute pathogen#infect()
filetype plugin indent on
filetype plugin on
syntax enable
syntax on
set autoindent
set autoread
set autowriteall
set backspace=indent,eol,start
set clipboard+=unnamed
set cmdheight=2
set complete-=i
set display+=lastline
set encoding=utf-8
set expandtab
set fileformats+=unix
set history=10240
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set linebreak
set nocursorcolumn
set nocursorline
set nojoinspaces
set nowrap
set number
set ruler
set scrolloff=4
set shell=/bin/bash
set shiftwidth=4
set shortmess=atI
set showcmd
set showmatch
set sidescrolloff=9
set smartcase
set smartindent
set smarttab
set softtabstop=4
set tabpagemax=9
set tabstop=4
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.log
set wildmenu
set wildmode=list:full

set path=**
set suffixesadd+=.py

" /usr/share/vim/vim73/keymap/russian-jcuken.vim
set keymap=russian-jcukeniv
" По умолчанию латинская раскладка
set iminsert=0
" По умолчанию латинская раскладка при поиске
set imsearch=0

"" Turn off swap files
set noswapfile
set nobackup
set updatecount=0

" viminfo options.txt 7577
set viminfo='4000,f100,<4400,:4800,@5500,/5900,%7700

" turn off octal numbers for <C-a>, <C-x>
set nrformats-=octal
set shiftround

set list
exec "set listchars=tab:›-,nbsp:~,trail:·,extends:>,precedes:<"

runtime macros/matchit.vim

"" Speed up macros
" set lazyredraw

"" Show full tags when doing search completion
"set showfulltag

autocmd FileType cfg set commentstring=#\ %s

""""""""""""""
""" Iv-specific
""""""""""""""

let mapleader=' '

" au WinLeave * set nocursorline
" au WinEnter * set cursorline

set background=dark

" set ttimeout
" set ttimeoutlen=50

let g:solarized_termtrans=1
colorscheme solarized

 highlight ColorColumn ctermbg=magenta ctermfg=black
 call matchadd('ColorColumn', '\%80v', 100)

highlight lCursor guifg=NONE guibg=Cyan

" set the status line to display some useful information
set stl=%<\ [%3*%n%H%M%R%W%*]\ %<%F
set stl+=\ %1*%{TagInStatusLineTag()}%*%=
set stl+=%5*%l%*/%L\ %5*%v%*

nnoremap <F7> :wall<cr>:VimuxRunLastCommand<cr>

" Join function arguments into one line
nnoremap <F3> :normal vabJ0%cs()kj<cr>

nnoremap [R Bi<cr><esc>
nnoremap ]R Wi<cr><esc>

nnoremap [r i<cr><esc>ge
nnoremap ]r a<cr><esc>ge

nnoremap <leader>T :!ctags --links=yes --tag-relative -R --exclude=.git --languages=-javascript,sql<cr>
nnoremap <leader>i :!isort %<cr>

nnoremap <leader>c :tabnew<cr>
nnoremap <leader>t mM:tabnew<cr>`M
nnoremap <leader>x :tabclose<cr>

nnoremap <leader><C-g> :Ggrep <C-r><C-w>

" rearrange arguments each to one line
nnoremap <leader>4  %mm%lc`m<cr><cr><c-o>k<c-r>"<esc>kmmjjmnk:s/\v\,\zs\s/\r/g<cr>`nv`m=

" Make underline text for markdown header
" ----------------------------------
nnoremap <leader>- yypVr-:<C-u>nohlsearch<cr><C-l>o

" Detect *.md files as markdown filetype
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" sort
nnoremap <Leader>s :sort i<cr>
vnoremap <Leader>s :sort i<cr>

" au FileType xml setlocal equalprg=xmllint\ --format\ --recover\ -\ 2>/dev/null
au FileType javascript setlocal equalprg=python\ -m\ json.tool\ 2>/dev/null

nnoremap <Leader>8 <esc>:!autopep8 --in-place --aggressive --aggressive %<cr>

" edit ~/.vim/colors/iv-color.vim
nnoremap <Leader>C :n ~/.vim/colors/iv-color.vim<cr>

" edit reload .vimrc
nnoremap <Leader>V :n ~/.vim/vimrc<cr>

" reload .vimrc
nnoremap <Leader>v :update<cr>:so $MYVIMRC<cr>
" autocmd BufWritePost ~/.vimrc   so ~/.vimrc

" git diff
nnoremap <Leader>d :!clear; git diff -U2 HEAD<cr>

" Strip trailing whitespace {{{2
function! Preserve(command)
" Preparation: save last search, and cursor position.
  let _s=@/
  let l = line(".")
  let c = col(".")
" Do the business:
  execute a:command
" Clean up: restore previous search history, and cursor position
  let @/=_s
  call cursor(l, c)
endfunction

function! GitAutocommitCurrentFile()
    :w!
    :lcd %:h
    :silent! !git reset
    :silent! !git add -f %
    :silent! !git commit -m '% autocommit'
    :lcd!
    :e!
    :redraw!
endfunction

nnoremap <leader>gc :call GitAutocommitCurrentFile()<cr>

" Python

" to python class begin
nnoremap [c ?^class <cr>

" strip trailing space in python files
" autocmd BufWritePre *.py normal m`:%s/\v\s+$//e<cr>``

function! TrimTrailingSpace()
    let save_cursor = getpos(".")
    :silent! %s#\v\s+$##e
    call setpos('.', save_cursor)
endfunction

nnoremap <leader>w :call TrimTrailingSpace()<cr>:w<cr>

" fast :w
nnoremap <Leader>W :w<cr>

" sudo save
nnoremap <Leader><C-w> :w !sudo tee % > /dev/null<cr>



""""""""""""""
""" Plugins settings
""""""""""""""

nnoremap <F2> :Pytest file<cr>

let g:syntastic_python_checkers=['pylint']
let g:syntastic_mode_map = { 'mode': 'passive' }

" mapping for tpope/vim-fugitive
nnoremap <Leader>G :Gstatus<cr>


" git-gutter
" To change the hunk-jumping maps:
nmap [h <Plug>GitGutterPrevHunk
nmap ]h <Plug>GitGutterNextHunk

" To change the hunk-staging/reverting maps:
nmap <Leader>hs <Plug>GitGutterStageHunk
nmap <Leader>hr <Plug>GitGutterRevertHunk

" TO TURN ON LINE HIGHLIGHTING BY DEFAULT
" let g:gitgutter_highlight_lines = 1



""""""""""""""
""" Useful
""""""""""""""

" ex_mode/history-scrollers.vim
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>

" hide search matches
nnoremap <silent><C-l> :<C-u>nohlsearch<cr><C-l>

" The & command is a synonym for :s, which repeats the last substitution. Unfortunately,
" if any flags were used, the & command disregards them, meaning that the outcome
"     could be quite different from the previous substitution.
"     Making & trigger the :&& command is more useful. It preserves flags and therefore
"     produces more consistent results. These mappings fix the & command in Normal
"     mode and create a Visual mode equivalent:
nnoremap & :&&<CR>
xnoremap & :&&<CR>

xnoremap . :normal .<CR>

inoremap <C-U> <C-G>u<C-U>


" LocationList toggle
nnoremap <leader>l :call LocationListToggle()<cr>
let g:location_list_is_open = 0
function! LocationListToggle()
    if g:location_list_is_open
        lclose
        let g:location_list_is_open = 0
        execute g:location_list_return_to_window . "wincmd w"
    else
        let g:location_list_return_to_window = winnr()
        lopen
        let g:location_list_is_open = 1
    endif
endfunction

" autocmd QuickFixCmdPost * bot cwindow " open quickfix at bottom

" qickfix toggle
nnoremap <leader>q :call QuickfixToggle()<cr>
let g:quickfix_is_open = 0
function! QuickfixToggle()
    if g:quickfix_is_open
        cclose
        let g:quickfix_is_open = 0
        execute g:quickfix_return_to_window . "wincmd w"
    else
        let g:quickfix_return_to_window = winnr()
        copen
        let g:quickfix_is_open = 1
    endif
endfunction

" quickfix autoheight
au FileType qf call AdjustWindowHeight(3, 21)
function! AdjustWindowHeight(minheight, maxheight)
    let l = 1
    let n_lines = 0
    let w_width = winwidth(0)
    while l <= line('$')
        " number to float for division
        let l_len = strlen(getline(l)) + 0.0
        let line_width = l_len/w_width
        let n_lines += float2nr(ceil(line_width))
        let l += 1
    endw
    exe max([min([n_lines, a:maxheight]), a:minheight]) . "wincmd _"
endfunction



""""""""""""""
""" TIPS
""""""""""""""

" go to defn of tag under the cursor
fun! MatchCaseTag()
    let ic = &ic
    set noic
    try
        exe 'tjump ' . expand('<cword>')
    finally
       let &ic = ic
    endtry
endfun
nnoremap <silent> <c-]> :call MatchCaseTag()<CR>

" TIP 'nelstrom/vim-visual-star-search'
" From http://got-ravings.blogspot.com/2008/07/vim-pr0n-visual-search-mappings.html
" makes * and # work on visual mode too.
function! s:VSetSearch(cmdtype)
  let temp = @s
  norm! gv"sy
  let @/ = '\V' . substitute(escape(@s, a:cmdtype.'\'), '\n', '\\n', 'g')
  let @s = temp
endfunction

xnoremap * :<C-u>call <SID>VSetSearch('/')<CR>/<C-R>=@/<CR><CR>
xnoremap # :<C-u>call <SID>VSetSearch('?')<CR>?<C-R>=@/<CR><CR>

" recursively vimgrep for word under cursor or selection if you hit leader-star
nmap <leader>* :execute 'noautocmd vimgrep /\V ' . substitute(escape(expand("<cword>"), '\'), '\n', '\\n', 'g') . '/ **/*.py'<CR>
vmap <leader>* :<C-u>call <SID>VSetSearch()<CR>:execute 'noautocmd vimgrep /' . @/ . '/ **/*.py'<CR>


" TIP 'nelstrom/vim-qargs'
command! -nargs=0 -bar Qargs execute 'args' QuickfixFilenames()
function! QuickfixFilenames()
  " Building a hash ensures we get each buffer only once
  let buffer_numbers = {}
  for quickfix_item in getqflist()
    let buffer_numbers[quickfix_item['bufnr']] = bufname(quickfix_item['bufnr'])
  endfor
  return join(map(values(buffer_numbers), 'fnameescape(v:val)'))
endfunction
