#!/bin/sh
set -e
trap "rm -f .git/tags.$$" EXIT
# ctags -c --links=no --tag-relative -Rf.git/tags.$$ --exclude=.git --languages=-javascript,sql
hasktags -c -R -o .git/tags.$$ .
mv .git/tags.$$ .git/tags
